site_name: USU.SU
site_url: https://usu.su
theme:
  name: material
  language: ru
  logo: assets/usu-logo.png
  favicon: assets/usu-logo.png
  # font:
  #   text: Roboto
  #   code: Roboto Mono
  palette:
    # - media: "(prefers-color-scheme)"
      # toggle:
        # icon: material/brightness-auto
        # name: Системная тема

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Светлая тема

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Темная тема
  features:
    - content.code.copy
    - search.highlight
    - search.suggest
extra:
  generator: false
extra_css:
  - assets/stylesheets/extra.css
markdown_extensions:
  - nl2br

  - admonition
  - pymdownx.details

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - glightbox
  - search
